TestCases:
  - Urls:
      - "https://host.docker.internal:32770/"
    Name: Startpage
    Users: 10
    Iterations: 10
    Delay: 1
#    UseCookies: false
    Init:
      Url: "https://host.docker.internal:32770/"

  - Urls:
      - "https://host.docker.internal:32770/Home/Privacy"
    Name: Privacy
    Users: 10
    Iterations: 10
    Delay: 1
    Init:
      Url: "https://host.docker.internal:32770/Home/Privacy"

  - Urls:
      - "https://host.docker.internal:32770/Home/Error"
    Name: Error
    Users: 10
    Iterations: 10
    Delay: 1
    Init:
      Url: "https://host.docker.internal:32770/Home/Error"