# image: docker:latest  # Use the latest Docker image
image: mcr.microsoft.com/dotnet/sdk:8.0

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: "$CI_REGISTRY/wickedflame/avalanche/avalanche-web:$CI_COMMIT_SHA"
  IMAGE_TAG_TOOL: "$CI_REGISTRY/wickedflame/avalanche/avalanche-tool:$CI_COMMIT_SHA"
  VERSION: 0.0.1

services:
  - docker:dind

stages:
  - build
  - test
  - deploy
  
build_solution:
  stage: build
  before_script:
    - dotnet tool install Nuke.GlobalTool --global
    - export PATH="$PATH:/root/.dotnet/tools"
  script:
  - dotnet restore Avalanche.sln
  - dotnet restore ./build/_build.csproj
  - nuke deploy -version $VERSION
  artifacts:
    paths:
      - artifacts/**/*.*

test_solution:
  stage: test
  script:
  - echo "test stage"
  only:
    - main
    - dev
    - merge_requests

deploy_web:
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -f dockerfile-web -t "$IMAGE_TAG" .
    - docker tag $IMAGE_TAG $CI_REGISTRY/wickedflame/avalanche/avalanche-web:latest
    - docker tag $IMAGE_TAG $CI_REGISTRY/wickedflame/avalanche/avalanche-web:$VERSION
    - docker push $CI_REGISTRY/wickedflame/avalanche/avalanche-web:latest
    - docker push $CI_REGISTRY/wickedflame/avalanche/avalanche-web:$VERSION
  only:
    - main
    - dev

deploy_tool:
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -f dockerfile-tool -t "$IMAGE_TAG_TOOL" .
    - docker tag $IMAGE_TAG_TOOL $CI_REGISTRY/wickedflame/avalanche/avalanche-tool:latest
    - docker tag $IMAGE_TAG_TOOL $CI_REGISTRY/wickedflame/avalanche/avalanche-tool:$VERSION
    - docker push $CI_REGISTRY/wickedflame/avalanche/avalanche-tool:latest
    - docker push $CI_REGISTRY/wickedflame/avalanche/avalanche-tool:$VERSION
  only:
    - main
    - dev