# image: docker:latest  # Use the latest Docker image
image: mcr.microsoft.com/dotnet/sdk:10.0

variables:
  IMAGE_TAG_CLIENT: "$CI_REGISTRY/wickedflame/avalanche/client:$CI_COMMIT_SHA"
  IMAGE_TAG_RUNNER: "$CI_REGISTRY/wickedflame/avalanche/runner:$CI_COMMIT_SHA"
  VERSION: 0.0.5

services:
  - docker:dind

stages:
  - build
  - test
  - deploy
  
build_solution:
  stage: build
  before_script:
    - dotnet tool install Nuke.GlobalTool --global --version 9.0.4
    - export PATH="$PATH:/root/.dotnet/tools"
  script:
  - dotnet restore Avalanche.sln
  - dotnet restore ./build/_build.csproj
  - nuke deploy -version $VERSION -buildno ${CI_PIPELINE_IID}
  artifacts:
    paths:
      - artifacts/**/*.*

test_solution:
  stage: test
  script:
  - echo "test stage"
  only:
    - master
    - dev
    - merge_requests


.deploy_client:
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  stage: deploy
  image: docker:latest
  services:
    - docker:dind

deploy_client_dev:
  only:
    - dev
  variables:
    IMAGE_TAG_CLIENT: "$CI_REGISTRY/wickedflame/avalanche/client:$CI_COMMIT_SHA"
  when: manual
  extends: .deploy_client
  script:
    - docker build -f dockerfile-client -t "$IMAGE_TAG_CLIENT" .
    - docker tag $IMAGE_TAG_CLIENT $CI_REGISTRY/wickedflame/avalanche/client:$VERSION-beta${CI_PIPELINE_IID}
    - docker push $CI_REGISTRY/wickedflame/avalanche/client:$VERSION-beta${CI_PIPELINE_IID}

deploy_client:
  only:
    - master
  extends: .deploy_client
  script:
    - docker build -f dockerfile-client -t "$IMAGE_TAG_CLIENT" .
    - docker tag $IMAGE_TAG_CLIENT $CI_REGISTRY/wickedflame/avalanche/client:latest
    - docker tag $IMAGE_TAG_CLIENT $CI_REGISTRY/wickedflame/avalanche/client:$VERSION
    - docker push $CI_REGISTRY/wickedflame/avalanche/client:latest
    - docker push $CI_REGISTRY/wickedflame/avalanche/client:$VERSION




.deploy_runner:
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  stage: deploy
  image: docker:latest
  services:
    - docker:dind

deploy_runner_dev:
  only:
    - dev
  variables:
    IMAGE_TAG_RUNNER: "$CI_REGISTRY/wickedflame/avalanche/runner:$CI_COMMIT_SHA-beta"
  when: manual
  extends: .deploy_runner
  script:
    - docker build -f dockerfile-runner -t "$IMAGE_TAG_RUNNER" .
    - docker tag $IMAGE_TAG_RUNNER $CI_REGISTRY/wickedflame/avalanche/runner:$VERSION
    - docker push $CI_REGISTRY/wickedflame/avalanche/runner:$VERSION

deploy_runner:
  only:
    - master
  extends: .deploy_runner
  script:
    - docker build -f dockerfile-runner -t "$IMAGE_TAG_RUNNER" .
    - docker tag $IMAGE_TAG_RUNNER $CI_REGISTRY/wickedflame/avalanche/runner:latest
    - docker tag $IMAGE_TAG_RUNNER $CI_REGISTRY/wickedflame/avalanche/runner:$VERSION
    - docker push $CI_REGISTRY/wickedflame/avalanche/runner:latest
    - docker push $CI_REGISTRY/wickedflame/avalanche/runner:$VERSION