FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env

WORKDIR /src

COPY . .
COPY .* .

FROM mcr.microsoft.com/dotnet/aspnet:8.0 as runtime

WORKDIR /app

COPY --from=build-env /src/artifacts/tool/ /app/

VOLUME /app/testfiles
# EXPOSE 8080

ENTRYPOINT ["dotnet", "/app/Avalanche.Tool.exe"]