TestCases:
  - Urls:
      - 'https://host.docker.internal:32770/'
    Name: Startpage
    Iterations: 10
    Users: 10
    Duration: 0
    Interval: 0
    RampupTime: 0
    UseCookies: True
    Delay: 1
    Init:
      Url: 'https://host.docker.internal:32770/'
  - Urls:
      - 'https://host.docker.internal:32770/Home/Privacy'
    Name: Privacy
    Iterations: 10
    Users: 10
    Duration: 0
    Interval: 0
    RampupTime: 0
    UseCookies: True
    Delay: 1
    Init:
      Url: 'https://host.docker.internal:32770/Home/Privacy'
  - Urls:
      - 'https://host.docker.internal:32770/Home/Error'
    Name: Error
    Iterations: 10
    Users: 10
    Duration: 0
    Interval: 0
    RampupTime: 0
    UseCookies: True
    Delay: 1
    Init:
      Url: 'https://host.docker.internal:32770/Home/Error'