<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
      <ImplicitUsings>enable</ImplicitUsings>
      <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
      <DocumentationFile>bin\Release\netstandard2.0\Avalanche.ReadModel.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
      <PackageReference Include="System.Data.SQLite" Version="1.0.119" />
  </ItemGroup>

</Project>
