<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.6" />
        <PackageReference Include="SqlKata" Version="4.0.1" />
        <PackageReference Include="SqlKata.Execution" Version="4.0.1" />
        <PackageReference Include="System.Data.SQLite" Version="1.0.119" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Avalanche.DataSource\Avalanche.DataSource.csproj" />
        <ProjectReference Include="..\Avalanche.WriteModel\Avalanche.WriteModel.csproj" />
        <ProjectReference Include="..\Broadcast\Broadcast.csproj" />
    </ItemGroup>

</Project>
