<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <RuntimeIdentifiers>linux-x64;win-x64</RuntimeIdentifiers>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>64a7eb2c-4e43-423b-bb54-83a04c54093c</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <DockerfileRunArguments>-p 32770:8081</DockerfileRunArguments>
        <DockerfileContext>..\..\..</DockerfileContext>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    </ItemGroup>

</Project>
