<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Avalanche.DataSource\Avalanche.DataSource.csproj" />
      <ProjectReference Include="..\Avalanche.ReadModel\Avalanche.ReadModel.csproj" />
    </ItemGroup>
</Project>
