<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RuntimeIdentifiers>linux-x64;win-x64</RuntimeIdentifiers>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>latest</LangVersion>


        <!--<SymbolPackageFormat>snupkg</SymbolPackageFormat>-->
        <!--<GeneratePackageOnBuild>true</GeneratePackageOnBuild>-->
        <Authors>Christian Walpen</Authors>
        <Company>WickedFlame</Company>
        <Description>LoadTest Component for Avalanche Test</Description>
        <Copyright>@WickedFlame 2025</Copyright>
        <PackageTags>Loadtests Stresstest Smoketest</PackageTags>
        <NeutralLanguage>de</NeutralLanguage>
        <Version>1.0.0.0</Version>
        <AssemblyVersion>1.0.0</AssemblyVersion>
        <FileVersion>1.0.0.0</FileVersion>
        <PackageVersion>1.0.0</PackageVersion>
        <InformationalVersion>1.0.0</InformationalVersion>
        <!--<Title>Avalanche</Title>-->
        <!--<PublishRepositoryUrl>true</PublishRepositoryUrl>-->
        <!--<PackageReadmeFile>README.md</PackageReadmeFile>-->
        <AssemblyName>Avalanche.Tool</AssemblyName>
        
        <!--<PackAsTool>true</PackAsTool>-->
        <!--<ToolCommandName>avalanche</ToolCommandName>-->
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <DockerfileContext>..\..</DockerfileContext>
    </PropertyGroup>

    <!--<PropertyGroup>
        <DockerfileRunArguments>-v ../../../../Avalanche/data:/data</DockerfileRunArguments>
    </PropertyGroup>-->

    <!--<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <DocumentationFile>bin\Release\netstandard2.0\Avalanche.Tool.xml</DocumentationFile>
    </PropertyGroup>-->

    <ItemGroup>
      <PackageReference Include="CommandLineParser" Version="2.9.1" />
      <PackageReference Include="MeasureMap" Version="3.0.0-RC13" />
      <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.6" />
      <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
      <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.12.0" />
      <PackageReference Include="YamlMap" Version="1.3.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Avalanche.Domain\Avalanche.Domain.csproj" />
      <ProjectReference Include="..\Avalanche.WriteModel.Memory\Avalanche.WriteModel.Memory.csproj" />
      <ProjectReference Include="..\Avalanche.WriteModel.RestClient\Avalanche.WriteModel.RestClient.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="scenarios\lab.yml">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="scenarios\LoadTest.yml">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="scenarios\local.yml">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
